### ISSUE TITLE
Optimization opportunities (tracking issue)

### ISSUE THREAD

**Issue by emilk** [emilk/egui#1196]
There is a lot of room for improvements to the CPU usage of egui. Here are some things worth investigating:

* [ ] Try different hash algorithms for `Id`, `FontCache` and others.
* [ ] Precompute vertices for circles and rounded corners in `epaint::Tessellator` constructor
* [ ] Run egui with a proper profiler and see what pops up
* https://github.com/emilk/egui/issues/1098
* [ ] Paint small filled circles using textured rects (by adding a few low-radius circles to the font atlas)

**Comment by emilk** [comment]
I added integration with [the puffin profiler](https://github.com/EmbarkStudios/puffin) in https://github.com/emilk/egui/pull/1483 to make it easier to a get a rough overview of app performance.

**Comment by YgorSouza** [comment]
This could be updated to link to #3862 and #1485, which have PRs in progress.
